name = "MultiStateSystems"
uuid = "63dd226a-9d27-42a2-9f4c-7f7a071798e0"
authors = ["Tom Van Acker"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
